import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, query, where, onSnapshot, addDoc, updateDoc, deleteDoc, doc, getDocs, getDoc, setDoc, arrayUnion, arrayRemove, serverTimestamp, runTransaction } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const firebaseConfig = {
  apiKey: 'TU_API_KEY',
  authDomain: 'TU_PROYECTO.firebaseapp.com',
  projectId: 'TU_PROJECT_ID',
  storageBucket: 'TU_PROYECTO.firebasestorage.app',
  messagingSenderId: 'TU_SENDER_ID',
  appId: 'TU_APP_ID'
};
const firebaseReady = !firebaseConfig.apiKey.startsWith('TU_') && !firebaseConfig.projectId.startsWith('TU_');
const app = firebaseReady ? initializeApp(firebaseConfig) : null;
const auth = app ? getAuth(app) : null;
const db = app ? getFirestore(app) : null;

const state = { user: null, counters: [], activeCounter: null, unsubscribeCounters: null, unsubscribeActive: null, demo: false, register: false };
const $ = (id) => document.getElementById(id);
const els = { authView: $('auth-view'), appView: $('app-view'), authForm: $('auth-form'), authTitle: $('auth-title'), authSubtitle: $('auth-subtitle'), authNameField: $('name-field'), authName: $('auth-name'), authEmail: $('auth-email'), authPassword: $('auth-password'), authSubmit: $('auth-submit'), authToggle: $('auth-toggle'), demoLogin: $('demo-login'), counterList: $('counter-list'), profileName: $('profile-name'), profileEmail: $('profile-email'), profileAvatar: $('profile-avatar'), userMenu: $('user-menu'), logout: $('logout'), newCounter: $('new-counter'), emptyNewCounter: $('empty-new-counter'), emptyState: $('empty-state'), counterWorkspace: $('counter-workspace'), counterTitle: $('counter-title'), counterMeta: $('counter-meta'), shareCounter: $('share-counter'), deleteCounter: $('delete-counter'), countNumber: $('count-number'), countLabel: $('count-label'), increment: $('increment'), decrement: $('decrement'), activityList: $('activity-list'), activityCount: $('activity-count'), memberList: $('member-list'), inviteMember: $('invite-member'), counterDialog: $('counter-dialog'), counterForm: $('counter-form'), counterName: $('counter-name'), counterUnit: $('counter-unit'), shareDialog: $('share-dialog'), shareForm: $('share-form'), memberEmail: $('member-email'), toast: $('toast'), connectionLabel: $('connection-label') };

function showToast(message, error = false) { els.toast.textContent = message; els.toast.className = `toast visible${error ? ' error' : ''}`; window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => { els.toast.className = 'toast'; }, 3200); }
function initials(name = 'Tu cuenta') { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); }
function timeAgo(date) { if (!date) return 'Ahora'; const value = date.toDate ? date.toDate() : new Date(date); const seconds = Math.floor((Date.now() - value.getTime()) / 1000); if (seconds < 60) return 'Ahora'; if (seconds < 3600) return `Hace ${Math.floor(seconds / 60)} min`; return `Hace ${Math.floor(seconds / 3600)} h`; }
function formatError(error) { const messages = { 'auth/invalid-credential': 'El correo o la contraseña no son correctos.', 'auth/email-already-in-use': 'Ese correo ya tiene una cuenta.', 'auth/weak-password': 'La contraseña debe tener al menos 6 caracteres.', 'auth/invalid-email': 'Revisa el formato del correo.' }; return messages[error.code] || 'No pudimos completar la operación. Inténtalo de nuevo.'; }
function setUser(user, demo = false) { state.user = user; state.demo = demo; const name = user.displayName || user.name || 'Tu cuenta'; els.profileName.textContent = name; els.profileEmail.textContent = user.email || 'modo demo'; els.profileAvatar.textContent = initials(name); els.userMenu.textContent = initials(name); els.connectionLabel.textContent = demo ? 'Modo demo' : 'Conectado'; els.authView.classList.add('hidden'); els.appView.classList.remove('hidden'); }
function resetApp() { state.activeCounter = null; els.counterWorkspace.classList.add('hidden'); els.emptyState.classList.remove('hidden'); els.counterTitle.textContent = 'Selecciona un contador'; els.counterMeta.textContent = 'Crea uno para comenzar.'; els.shareCounter.disabled = true; els.deleteCounter.disabled = true; }
function demoData() { try { return JSON.parse(localStorage.getItem('cuenta-juntos-demo') || 'null') || { counters: [{ id: 'demo-1', name: 'Cajas recibidas', unit: 'cajas', count: 24, ownerId: 'demo', memberIds: ['demo'], members: [{ email: 'tú', name: 'Tú', role: 'Propietario' }], activity: [{ delta: 1, by: 'Tú', at: Date.now() }] }] }; } catch { return { counters: [] }; } }
function saveDemo(data) { localStorage.setItem('cuenta-juntos-demo', JSON.stringify(data)); }
function demoCounters() { state.counters = demoData().counters; renderCounterList(); if (!state.activeCounter && state.counters[0]) selectCounter(state.counters[0].id); }
function renderCounterList() { els.counterList.innerHTML = ''; if (!state.counters.length) { els.counterList.innerHTML = '<p class="muted">Aún no tienes contadores.</p>'; resetApp(); return; } state.counters.forEach((counter) => { const button = document.createElement('button'); button.className = `counter-item${state.activeCounter?.id === counter.id ? ' active' : ''}`; button.type = 'button'; button.innerHTML = `<span class="counter-icon">#</span><span>${escapeHtml(counter.name)}<small class="counter-item-meta">${counter.count || 0} ${escapeHtml(counter.unit || 'objetos')}</small></span>`; button.addEventListener('click', () => selectCounter(counter.id)); els.counterList.appendChild(button); }); }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
async function loadCounters() { if (state.demo) { demoCounters(); return; } if (state.unsubscribeCounters) state.unsubscribeCounters(); const countersQuery = query(collection(db, 'counters'), where('memberIds', 'array-contains', state.user.uid)); state.unsubscribeCounters = onSnapshot(countersQuery, (snapshot) => { state.counters = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); renderCounterList(); if (!state.activeCounter && state.counters[0]) selectCounter(state.counters[0].id); if (state.activeCounter && !state.counters.some((item) => item.id === state.activeCounter.id)) resetApp(); }, () => showToast('No pudimos cargar tus contadores.', true)); }
function selectCounter(id) { const counter = state.counters.find((item) => item.id === id); if (!counter) return; state.activeCounter = counter; renderCounterList(); renderActiveCounter(counter); if (!state.demo) subscribeActiveCounter(id); }
function subscribeActiveCounter(id) { if (state.unsubscribeActive) state.unsubscribeActive(); state.unsubscribeActive = onSnapshot(doc(db, 'counters', id), (snapshot) => { if (snapshot.exists()) { state.activeCounter = { id: snapshot.id, ...snapshot.data() }; renderActiveCounter(state.activeCounter); } }); }
function renderActiveCounter(counter) { els.emptyState.classList.add('hidden'); els.counterWorkspace.classList.remove('hidden'); els.counterTitle.textContent = counter.name; els.counterMeta.textContent = `Actualizado ${timeAgo(counter.updatedAt || counter.activity?.[counter.activity.length - 1]?.at)}`; els.shareCounter.disabled = false; els.deleteCounter.disabled = counter.ownerId !== state.user.uid && !state.demo; els.countNumber.textContent = counter.count || 0; els.countLabel.textContent = counter.unit || 'objetos'; els.activityCount.textContent = counter.activity?.length || 0; els.activityList.innerHTML = ''; (counter.activity || []).slice().reverse().slice(0, 8).forEach((item) => { const row = document.createElement('div'); row.className = 'activity-row'; const positive = item.delta > 0; row.innerHTML = `<span class="activity-symbol${positive ? '' : ' minus'}">${positive ? '+' : '−'}</span><span class="activity-text"><strong>${escapeHtml(item.by || 'Alguien')}</strong> ${positive ? 'sumó' : 'restó'} ${Math.abs(item.delta)}</span><span class="activity-time">${timeAgo(item.at)}</span>`; els.activityList.appendChild(row); }); if (!counter.activity?.length) els.activityList.innerHTML = '<p class="muted">Los movimientos aparecerán aquí.</p>'; renderMembers(counter); }
function renderMembers(counter) { els.memberList.innerHTML = ''; const members = counter.members || [{ name: 'Tú', email: state.user.email, role: 'Propietario' }]; members.forEach((member) => { const row = document.createElement('div'); row.className = 'member-row'; row.innerHTML = `<span class="member-avatar">${initials(member.name || member.email)}</span><span class="member-info"><strong>${escapeHtml(member.name || member.email)}</strong><span>${escapeHtml(member.role || 'Colaborador')} · ${escapeHtml(member.email || '')}</span></span>`; els.memberList.appendChild(row); }); }
async function changeCount(delta) { const counter = state.activeCounter; if (!counter) return; const actor = state.user.displayName || state.user.name || 'Tú'; const activity = { delta, by: actor, at: Date.now() }; if (state.demo) { const data = demoData(); const target = data.counters.find((item) => item.id === counter.id); target.count = Math.max(0, (target.count || 0) + delta); target.activity = [...(target.activity || []), activity].slice(-30); saveDemo(data); state.counters = data.counters; state.activeCounter = target; renderCounterList(); renderActiveCounter(target); return; } try { await runTransaction(db, async (transaction) => { const ref = doc(db, 'counters', counter.id); const snapshot = await transaction.get(ref); const current = snapshot.data()?.count || 0; transaction.update(ref, { count: Math.max(0, current + delta), activity: arrayUnion(activity), updatedAt: serverTimestamp() }); }); } catch { showToast('No se pudo actualizar el conteo.', true); } }
async function createCounter(event) { event.preventDefault(); const name = els.counterName.value.trim(); const unit = els.counterUnit.value.trim() || 'objetos'; if (!name) return; if (state.demo) { const data = demoData(); const counter = { id: `demo-${Date.now()}`, name, unit, count: 0, ownerId: 'demo', memberIds: ['demo'], members: [{ email: 'tú', name: 'Tú', role: 'Propietario' }], activity: [] }; data.counters.push(counter); saveDemo(data); els.counterDialog.close(); els.counterForm.reset(); state.counters = data.counters; selectCounter(counter.id); renderCounterList(); showToast('Contador creado'); return; } try { const newCounter = await addDoc(collection(db, 'counters'), { name, unit, count: 0, ownerId: state.user.uid, memberIds: [state.user.uid], members: [{ email: state.user.email, name: state.user.displayName || 'Propietario', role: 'Propietario' }], activity: [], createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); els.counterDialog.close(); els.counterForm.reset(); showToast('Contador creado'); selectCounter(newCounter.id); } catch { showToast('No se pudo crear el contador.', true); } }
async function deleteCounter() { const counter = state.activeCounter; if (!counter || (!state.demo && counter.ownerId !== state.user.uid)) return showToast('Solo el propietario puede eliminarlo.', true); if (!window.confirm(`¿Eliminar “${counter.name}”?`)) return; if (state.demo) { const data = demoData(); data.counters = data.counters.filter((item) => item.id !== counter.id); saveDemo(data); state.counters = data.counters; state.activeCounter = null; renderCounterList(); return; } try { await deleteDoc(doc(db, 'counters', counter.id)); state.activeCounter = null; showToast('Contador eliminado'); } catch { showToast('No se pudo eliminar.', true); } }
async function inviteMember(event) { event.preventDefault(); const email = els.memberEmail.value.trim().toLowerCase(); if (!email || !state.activeCounter) return; if (state.demo) { const data = demoData(); const target = data.counters.find((item) => item.id === state.activeCounter.id); target.members = [...(target.members || []), { email, name: email.split('@')[0], role: 'Colaborador' }]; saveDemo(data); state.counters = data.counters; state.activeCounter = target; els.shareDialog.close(); els.shareForm.reset(); renderActiveCounter(target); showToast('Invitación simulada'); return; } try { const users = await getDocs(query(collection(db, 'users'), where('email', '==', email))); if (users.empty) return showToast('Esa persona debe registrarse primero.', true); const invited = users.docs[0]; const invitedData = invited.data(); await updateDoc(doc(db, 'counters', state.activeCounter.id), { memberIds: arrayUnion(invited.id), members: arrayUnion({ email, name: invitedData.name || email.split('@')[0], role: 'Colaborador' }) }); els.shareDialog.close(); els.shareForm.reset(); showToast('Acceso concedido'); } catch { showToast('No se pudo invitar a esa persona.', true); } }
async function handleAuth(event) { event.preventDefault(); if (!firebaseReady) return showToast('Configura Firebase para usar el acceso real.', true); const email = els.authEmail.value.trim().toLowerCase(); const password = els.authPassword.value; try { if (!state.register) await signInWithEmailAndPassword(auth, email, password); else { const credentials = await createUserWithEmailAndPassword(auth, email, password); const name = els.authName.value.trim() || email.split('@')[0]; await updateProfile(credentials.user, { displayName: name }); await setDoc(doc(db, 'users', credentials.user.uid), { email, name }); } } catch (error) { showToast(formatError(error), true); } }
function toggleAuth() { state.register = !state.register; els.authNameField.classList.toggle('hidden', !state.register); els.authTitle.textContent = state.register ? 'Crea tu cuenta' : 'Bienvenido'; els.authSubtitle.textContent = state.register ? 'Empieza a compartir tus conteos.' : 'Inicia sesión para ver tus contadores.'; els.authSubmit.textContent = state.register ? 'Crear cuenta' : 'Entrar'; els.authToggle.textContent = state.register ? '¿Ya tienes cuenta? Inicia sesión' : '¿No tienes cuenta? Regístrate'; }
function logout() { if (state.demo) { state.demo = false; state.user = null; els.appView.classList.add('hidden'); els.authView.classList.remove('hidden'); return; } signOut(auth); }
function startDemo() { setUser({ name: 'Modo demo', email: 'Tus datos quedan en este navegador' }, true); loadCounters(); }

els.authForm.addEventListener('submit', handleAuth); els.authToggle.addEventListener('click', toggleAuth); els.demoLogin.addEventListener('click', startDemo); els.newCounter.addEventListener('click', () => els.counterDialog.showModal()); els.emptyNewCounter.addEventListener('click', () => els.counterDialog.showModal()); els.counterForm.addEventListener('submit', createCounter); els.shareCounter.addEventListener('click', () => els.shareDialog.showModal()); els.inviteMember.addEventListener('click', () => els.shareDialog.showModal()); els.shareForm.addEventListener('submit', inviteMember); els.increment.addEventListener('click', () => changeCount(1)); els.decrement.addEventListener('click', () => changeCount(-1)); els.deleteCounter.addEventListener('click', deleteCounter); els.logout.addEventListener('click', logout); els.userMenu.addEventListener('click', logout); document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea')) return; if (event.key === '+' || event.key === '=') changeCount(1); if (event.key === '-' || event.key === '_') changeCount(-1); });

if (firebaseReady) { onAuthStateChanged(auth, (user) => { if (user) { setUser(user); loadCounters(); } }); } else { els.connectionLabel.textContent = 'Sin configurar'; }
