import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getAuth, onAuthStateChanged, signInWithEmailAndPassword, createUserWithEmailAndPassword, updateProfile, signOut } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js';
import { getFirestore, collection, query, where, orderBy, onSnapshot, addDoc, updateDoc, deleteDoc, doc, getDocs, getDoc, setDoc, arrayUnion, arrayRemove, serverTimestamp, runTransaction } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js';

const firebaseConfig = {
  apiKey: "AIzaSyAhWhaYQhd701jRf5IbS772Tw8qC3PDrrI",
  authDomain: "contador-compartido.firebaseapp.com",
  projectId: "contador-compartido",
  storageBucket: "contador-compartido.firebasestorage.app",
  messagingSenderId: "596927392199",
  appId: "1:596927392199:web:c11bfc5287aa29bf5391e2"
};
const firebaseReady = !firebaseConfig.apiKey.startsWith('TU_') && !firebaseConfig.projectId.startsWith('TU_');
const app = firebaseReady ? initializeApp(firebaseConfig) : null;
const auth = app ? getAuth(app) : null;
const db = app ? getFirestore(app) : null;

const state = { user: null, counters: [], activeCounter: null, events: [], unsubscribeCounters: null, unsubscribeActive: null, unsubscribeEvents: null, demo: false, register: false, recentCounterId: null, recentTimer: null };
const $ = (id) => document.getElementById(id);
const els = { authView: $('auth-view'), appView: $('app-view'), authForm: $('auth-form'), authTitle: $('auth-title'), authSubtitle: $('auth-subtitle'), authNameField: $('name-field'), authName: $('auth-name'), authEmail: $('auth-email'), authPassword: $('auth-password'), authSubmit: $('auth-submit'), authToggle: $('auth-toggle'), demoLogin: $('demo-login'), counterList: $('counter-list'), counterSearch: $('counter-search'), counterDate: $('counter-date'), profileName: $('profile-name'), profileEmail: $('profile-email'), profileAvatar: $('profile-avatar'), userMenu: $('user-menu'), logout: $('logout'), newCounter: $('new-counter'), emptyNewCounter: $('empty-new-counter'), emptyState: $('empty-state'), counterWorkspace: $('counter-workspace'), counterTitle: $('counter-title'), counterMeta: $('counter-meta'), shareCounter: $('share-counter'), deleteCounter: $('delete-counter'), countNumber: $('count-number'), countLabel: $('count-label'), increment: $('increment'), decrement: $('decrement'), activityList: $('activity-list'), activityCount: $('activity-count'), activitySearch: $('activity-search'), activityFrom: $('activity-from'), activityTo: $('activity-to'), memberList: $('member-list'), inviteMember: $('invite-member'), counterDialog: $('counter-dialog'), counterForm: $('counter-form'), counterName: $('counter-name'), counterUnit: $('counter-unit'), closeCounterDialog: $('close-counter-dialog'), cancelCounterDialog: $('cancel-counter-dialog'), shareDialog: $('share-dialog'), shareForm: $('share-form'), memberEmail: $('member-email'), closeShareDialog: $('close-share-dialog'), cancelShareDialog: $('cancel-share-dialog'), toast: $('toast'), connectionLabel: $('connection-label') };

function showToast(message, error = false) { els.toast.textContent = message; els.toast.className = `toast visible${error ? ' error' : ''}`; window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => { els.toast.className = 'toast'; }, 3200); }
function initials(name = 'Tu cuenta') { return name.split(/\s+/).filter(Boolean).slice(0, 2).map((part) => part[0]).join('').toUpperCase(); }
function timeAgo(date) { if (!date) return 'Ahora'; const value = date.toDate ? date.toDate() : new Date(date); const seconds = Math.floor((Date.now() - value.getTime()) / 1000); if (seconds < 60) return 'Ahora'; if (seconds < 3600) return `Hace ${Math.floor(seconds / 60)} min`; return `Hace ${Math.floor(seconds / 3600)} h`; }
function timestampValue(value) { if (!value) return 0; const date = value.toDate ? value.toDate() : new Date(value); return Number.isNaN(date.getTime()) ? 0 : date.getTime(); }
function formatDate(value) { const time = timestampValue(value); return time ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(time)) : 'Fecha pendiente'; }
function formatError(error) { const messages = { 'auth/invalid-credential': 'El correo o la contraseña no son correctos.', 'auth/email-already-in-use': 'Ese correo ya tiene una cuenta.', 'auth/weak-password': 'La contraseña debe tener al menos 6 caracteres.', 'auth/invalid-email': 'Revisa el formato del correo.' }; return messages[error.code] || 'No pudimos completar la operación. Inténtalo de nuevo.'; }
function getCounterActivityTime(counter) { if (!counter) return 0; const updated = timestampValue(counter.updatedAt); const lastAct = counter.activity?.length ? timestampValue(counter.activity[counter.activity.length - 1].at) : 0; const created = timestampValue(counter.createdAt); return Math.max(updated, lastAct, created); }
function markCounterRecent(id) { state.recentCounterId = id; if (state.recentTimer) window.clearTimeout(state.recentTimer); state.recentTimer = window.setTimeout(() => { state.recentCounterId = null; renderCounterList(); }, 4000); }
function setUser(user, demo = false) { state.user = user; state.demo = demo; const name = user.displayName || user.name || 'Tu cuenta'; els.profileName.textContent = name; els.profileEmail.textContent = user.email || 'modo demo'; els.profileAvatar.textContent = initials(name); els.userMenu.textContent = initials(name); els.connectionLabel.textContent = demo ? 'Modo demo' : 'Conectado'; els.authView.classList.add('hidden'); els.appView.classList.remove('hidden'); }
function resetApp() { state.activeCounter = null; els.counterWorkspace.classList.add('hidden'); els.emptyState.classList.remove('hidden'); els.counterTitle.textContent = 'Selecciona un contador'; els.counterMeta.textContent = 'Crea uno para comenzar.'; els.shareCounter.disabled = true; els.deleteCounter.disabled = true; }
function demoData() { try { return JSON.parse(localStorage.getItem('cuenta-juntos-demo') || 'null') || { counters: [{ id: 'demo-1', name: 'Cajas recibidas', unit: 'cajas', count: 24, ownerId: 'demo', memberIds: ['demo'], createdAt: Date.now(), updatedAt: Date.now(), members: [{ email: 'tú', name: 'Tú', role: 'Propietario' }], activity: [{ delta: 1, by: 'Tú', at: Date.now() }] }] }; } catch { return { counters: [] }; } }
function saveDemo(data) { localStorage.setItem('cuenta-juntos-demo', JSON.stringify(data)); }
function demoCounters() { state.counters = demoData().counters; renderCounterList(); if (!state.activeCounter && state.counters[0]) selectCounter(state.counters[0].id); }
function renderCounterList() { els.counterList.innerHTML = ''; const search = els.counterSearch.value.trim().toLowerCase(); const selectedDate = els.counterDate.value; const counters = state.counters.filter((counter) => { const matchesSearch = `${counter.name} ${counter.unit || ''}`.toLowerCase().includes(search); const createdTime = timestampValue(counter.createdAt); const matchesDate = !selectedDate || (createdTime && new Date(createdTime).toISOString().slice(0, 10) === selectedDate); return matchesSearch && matchesDate; }).sort((first, second) => getCounterActivityTime(second) - getCounterActivityTime(first)); if (!counters.length) { els.counterList.innerHTML = `<p class="muted">${state.counters.length ? 'No hay coincidencias.' : 'Aún no tienes contadores.'}</p>`; if (!state.counters.length) resetApp(); return; } counters.forEach((counter) => { const isRecent = state.recentCounterId === counter.id; const button = document.createElement('button'); button.className = `counter-item${state.activeCounter?.id === counter.id ? ' active' : ''}${isRecent ? ' just-updated' : ''}`; button.type = 'button'; const recentBadge = isRecent ? `<span class="recent-badge"><span class="recent-dot"></span>Reciente</span>` : ''; const lastActive = getCounterActivityTime(counter); button.innerHTML = `<span class="counter-icon">#</span><span class="counter-item-content"><strong>${escapeHtml(counter.name)}</strong><small class="counter-item-meta">${counter.count || 0} ${escapeHtml(counter.unit || 'objetos')}</small><small class="counter-item-date">${lastActive ? `Actividad: ${timeAgo(lastActive)}` : `Creado: ${formatDate(counter.createdAt)}`}</small></span>${recentBadge}`; button.addEventListener('click', () => selectCounter(counter.id)); els.counterList.appendChild(button); }); if (state.recentCounterId) { els.counterList.scrollTo({ top: 0, left: 0, behavior: 'smooth' }); } }
function escapeHtml(value = '') { return String(value).replace(/[&<>'"]/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#039;', '"': '&quot;' }[char])); }
async function loadCounters() { if (state.demo) { demoCounters(); return; } if (state.unsubscribeCounters) state.unsubscribeCounters(); const countersQuery = query(collection(db, 'counters'), where('memberIds', 'array-contains', state.user.uid)); state.unsubscribeCounters = onSnapshot(countersQuery, (snapshot) => { snapshot.docChanges().forEach((change) => { if (change.type === 'modified') { markCounterRecent(change.doc.id); } }); state.counters = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); renderCounterList(); if (!state.activeCounter && state.counters.length) selectCounter(state.counters.slice().sort((first, second) => getCounterActivityTime(second) - getCounterActivityTime(first))[0].id); if (state.activeCounter && !state.counters.some((item) => item.id === state.activeCounter.id)) resetApp(); }, () => showToast('No pudimos cargar tus contadores.', true)); }
function selectCounter(id) { const counter = state.counters.find((item) => item.id === id); if (!counter) return; state.activeCounter = counter; state.events = []; renderCounterList(); renderActiveCounter(counter); const activeEl = els.counterList.querySelector('.counter-item.active'); if (activeEl) { activeEl.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'nearest' }); } if (state.demo) { state.events = (counter.activity || []).slice().reverse(); renderActivity(); } else { subscribeActiveCounter(id); subscribeEvents(id); } }
function subscribeActiveCounter(id) { if (state.unsubscribeActive) state.unsubscribeActive(); state.unsubscribeActive = onSnapshot(doc(db, 'counters', id), (snapshot) => { if (snapshot.exists()) { state.activeCounter = { id: snapshot.id, ...snapshot.data() }; renderActiveCounter(state.activeCounter); } }); }
function renderActiveCounter(counter) { els.emptyState.classList.add('hidden'); els.counterWorkspace.classList.remove('hidden'); els.counterTitle.textContent = counter.name; els.counterMeta.textContent = `Actualizado ${timeAgo(counter.updatedAt || counter.activity?.[counter.activity.length - 1]?.at)}`; els.shareCounter.disabled = false; els.deleteCounter.disabled = counter.ownerId !== state.user.uid && !state.demo; els.countNumber.textContent = counter.count || 0; els.countNumber.classList.remove('bump'); void els.countNumber.offsetWidth; els.countNumber.classList.add('bump'); els.countLabel.textContent = counter.unit || 'objetos'; renderActivity(); renderMembers(counter); }
function eventDate(item) { if (item.createdAt?.toDate) return item.createdAt.toDate(); if (item.at) return new Date(item.at); return null; }
function formatDateTime(item) { const date = eventDate(item); return date ? new Intl.DateTimeFormat('es-ES', { dateStyle: 'medium', timeStyle: 'medium' }).format(date) : 'Registrando...'; }
function renderActivity() { const search = els.activitySearch.value.trim().toLowerCase(); const from = els.activityFrom.value ? new Date(`${els.activityFrom.value}T00:00:00`) : null; const to = els.activityTo.value ? new Date(`${els.activityTo.value}T23:59:59`) : null; const events = state.events.filter((item) => { const date = eventDate(item); const text = `${item.by || ''} ${item.delta > 0 ? 'sumó' : 'restó'}`.toLowerCase(); return (!search || text.includes(search)) && (!from || (date && date >= from)) && (!to || (date && date <= to)); }); els.activityCount.textContent = events.length; els.activityList.innerHTML = ''; events.forEach((item) => { const row = document.createElement('div'); row.className = 'activity-row'; const positive = item.delta > 0; row.innerHTML = `<span class="activity-symbol${positive ? '' : ' minus'}">${positive ? '+' : '−'}</span><span class="activity-text"><strong>${escapeHtml(item.by || 'Alguien')}</strong> ${positive ? 'sumó' : 'restó'} ${Math.abs(item.delta)}<small>${formatDateTime(item)}</small></span><span class="activity-time">${timeAgo(eventDate(item))}</span>`; els.activityList.appendChild(row); }); if (!events.length) els.activityList.innerHTML = '<p class="muted">No hay movimientos para este filtro.</p>'; }
function subscribeEvents(id) { if (state.unsubscribeEvents) state.unsubscribeEvents(); state.unsubscribeEvents = onSnapshot(query(collection(db, 'counters', id, 'events'), orderBy('createdAt', 'desc')), (snapshot) => { state.events = snapshot.docs.map((item) => ({ id: item.id, ...item.data() })); if (!state.events.length) state.events = (state.activeCounter?.activity || []).slice().reverse(); renderActivity(); }, () => showToast('No pudimos cargar el historial.', true)); }
function renderMembers(counter) { els.memberList.innerHTML = ''; const members = counter.members || [{ name: 'Tú', email: state.user.email, role: 'Propietario' }]; members.forEach((member) => { const row = document.createElement('div'); row.className = 'member-row'; row.innerHTML = `<span class="member-avatar">${initials(member.name || member.email)}</span><span class="member-info"><strong>${escapeHtml(member.name || member.email)}</strong><span>${escapeHtml(member.role || 'Colaborador')} · ${escapeHtml(member.email || '')}</span></span>`; els.memberList.appendChild(row); }); }
async function changeCount(delta) { const counter = state.activeCounter; if (!counter) return; const actor = state.user.displayName || state.user.name || 'Tú'; const now = Date.now(); const activity = { delta, by: actor, actorId: state.user.uid || 'demo', at: now }; markCounterRecent(counter.id); if (state.demo) { const data = demoData(); const target = data.counters.find((item) => item.id === counter.id); target.count = Math.max(0, (target.count || 0) + delta); target.activity = [...(target.activity || []), activity]; target.updatedAt = now; saveDemo(data); state.counters = data.counters; state.activeCounter = target; state.events = target.activity.slice().reverse(); renderCounterList(); renderActiveCounter(target); return; } try { await runTransaction(db, async (transaction) => { const ref = doc(db, 'counters', counter.id); const snapshot = await transaction.get(ref); const current = snapshot.data()?.count || 0; transaction.update(ref, { count: Math.max(0, current + delta), activity: arrayUnion(activity), updatedAt: serverTimestamp() }); }); await addDoc(collection(db, 'counters', counter.id, 'events'), { ...activity, createdAt: serverTimestamp() }); } catch { showToast('No se pudo actualizar el conteo.', true); } }
async function createCounter(event) { event.preventDefault(); const name = els.counterName.value.trim(); const unit = els.counterUnit.value.trim() || 'objetos'; if (!name) return; if (state.demo) { const data = demoData(); const now = Date.now(); const counter = { id: `demo-${now}`, name, unit, count: 0, ownerId: 'demo', memberIds: ['demo'], createdAt: now, updatedAt: now, members: [{ email: 'tú', name: 'Tú', role: 'Propietario' }], activity: [] }; data.counters.push(counter); saveDemo(data); els.counterDialog.close(); els.counterForm.reset(); state.counters = data.counters; markCounterRecent(counter.id); selectCounter(counter.id); renderCounterList(); showToast('Contador creado'); return; } try { const newCounter = await addDoc(collection(db, 'counters'), { name, unit, count: 0, ownerId: state.user.uid, memberIds: [state.user.uid], members: [{ email: state.user.email, name: state.user.displayName || 'Propietario', role: 'Propietario' }], activity: [], createdAt: serverTimestamp(), updatedAt: serverTimestamp() }); els.counterDialog.close(); els.counterForm.reset(); showToast('Contador creado'); markCounterRecent(newCounter.id); selectCounter(newCounter.id); } catch { showToast('No se pudo crear el contador.', true); } }
async function deleteCounter() { const counter = state.activeCounter; if (!counter || (!state.demo && counter.ownerId !== state.user.uid)) return showToast('Solo el propietario puede eliminarlo.', true); if (!window.confirm(`¿Eliminar “${counter.name}”?`)) return; if (state.demo) { const data = demoData(); data.counters = data.counters.filter((item) => item.id !== counter.id); saveDemo(data); state.counters = data.counters; state.activeCounter = null; renderCounterList(); return; } try { await deleteDoc(doc(db, 'counters', counter.id)); state.activeCounter = null; showToast('Contador eliminado'); } catch { showToast('No se pudo eliminar.', true); } }
async function inviteMember(event) { event.preventDefault(); const email = els.memberEmail.value.trim().toLowerCase(); if (!email || !state.activeCounter) return; if (state.demo) { const data = demoData(); const target = data.counters.find((item) => item.id === state.activeCounter.id); target.members = [...(target.members || []), { email, name: email.split('@')[0], role: 'Colaborador' }]; saveDemo(data); state.counters = data.counters; state.activeCounter = target; els.shareDialog.close(); els.shareForm.reset(); renderActiveCounter(target); showToast('Invitación simulada'); return; } try { const users = await getDocs(query(collection(db, 'users'), where('email', '==', email))); if (users.empty) return showToast('Esa persona debe registrarse primero.', true); const invited = users.docs[0]; const invitedData = invited.data(); await updateDoc(doc(db, 'counters', state.activeCounter.id), { memberIds: arrayUnion(invited.id), members: arrayUnion({ email, name: invitedData.name || email.split('@')[0], role: 'Colaborador' }) }); els.shareDialog.close(); els.shareForm.reset(); showToast('Acceso concedido'); } catch { showToast('No se pudo invitar a esa persona.', true); } }
async function handleAuth(event) { event.preventDefault(); if (!firebaseReady) return showToast('Configura Firebase para usar el acceso real.', true); const email = els.authEmail.value.trim().toLowerCase(); const password = els.authPassword.value; try { if (!state.register) await signInWithEmailAndPassword(auth, email, password); else { const credentials = await createUserWithEmailAndPassword(auth, email, password); const name = els.authName.value.trim() || email.split('@')[0]; await updateProfile(credentials.user, { displayName: name }); await setDoc(doc(db, 'users', credentials.user.uid), { email, name }); } } catch (error) { showToast(formatError(error), true); } }
function toggleAuth() { state.register = !state.register; els.authNameField.classList.toggle('hidden', !state.register); els.authTitle.textContent = state.register ? 'Crea tu cuenta' : 'Bienvenido'; els.authSubtitle.textContent = state.register ? 'Empieza a compartir tus conteos.' : 'Inicia sesión para ver tus contadores.'; els.authSubmit.textContent = state.register ? 'Crear cuenta' : 'Entrar'; els.authToggle.textContent = state.register ? '¿Ya tienes cuenta? Inicia sesión' : '¿No tienes cuenta? Regístrate'; }
function logout() { if (state.demo) { state.demo = false; state.user = null; els.appView.classList.add('hidden'); els.authView.classList.remove('hidden'); return; } signOut(auth); }
function startDemo() { setUser({ name: 'Modo demo', email: 'Tus datos quedan en este navegador' }, true); loadCounters(); }

els.counterList.addEventListener('wheel', (e) => { if (els.counterList.scrollWidth > els.counterList.clientWidth && Math.abs(e.deltaY) > Math.abs(e.deltaX)) { els.counterList.scrollLeft += e.deltaY; } }, { passive: true }); els.authForm.addEventListener('submit', handleAuth); els.authToggle.addEventListener('click', toggleAuth); els.demoLogin.addEventListener('click', startDemo); els.counterSearch.addEventListener('input', renderCounterList); els.counterDate.addEventListener('change', renderCounterList); els.activitySearch.addEventListener('input', renderActivity); els.activityFrom.addEventListener('change', renderActivity); els.activityTo.addEventListener('change', renderActivity); els.newCounter.addEventListener('click', () => els.counterDialog.showModal()); els.emptyNewCounter.addEventListener('click', () => els.counterDialog.showModal()); els.counterForm.addEventListener('submit', createCounter); els.closeCounterDialog.addEventListener('click', () => els.counterDialog.close()); els.cancelCounterDialog.addEventListener('click', () => els.counterDialog.close()); els.shareCounter.addEventListener('click', () => els.shareDialog.showModal()); els.inviteMember.addEventListener('click', () => els.shareDialog.showModal()); els.shareForm.addEventListener('submit', inviteMember); els.closeShareDialog.addEventListener('click', () => els.shareDialog.close()); els.cancelShareDialog.addEventListener('click', () => els.shareDialog.close()); els.increment.addEventListener('click', () => changeCount(1)); els.decrement.addEventListener('click', () => changeCount(-1)); els.deleteCounter.addEventListener('click', deleteCounter); els.logout.addEventListener('click', logout); els.userMenu.addEventListener('click', logout); document.addEventListener('keydown', (event) => { if (event.target.matches('input, textarea')) return; if (event.key === '+' || event.key === '=') changeCount(1); if (event.key === '-' || event.key === '_') changeCount(-1); });

if ('serviceWorker' in navigator) window.addEventListener('load', () => navigator.serviceWorker.register('./sw.js').catch(() => {}));

if (firebaseReady) { onAuthStateChanged(auth, (user) => { if (user) { setUser(user); loadCounters(); } }); } else { els.connectionLabel.textContent = 'Sin configurar'; }
